export default function decorate(block) {
    const container = document.createElement('div');
    container.setAttribute('class', 'container');
    const divEl = document.createElement('div');
    divEl.setAttribute('id', 'experiencefragment-48166e81d0');
    divEl.setAttribute('class', 'cmp-experiencefragment cmp-experiencefragment--footer');
    const divEl2 = document.createElement('div');
    divEl2.setAttribute('id', 'container-8ed12ca4ce');
    divEl2.setAttribute('class', 'cmp-container');
    divEl2.setAttribute('style', 'background-image:url()');
    const divEl3 = document.createElement('div');
    divEl3.setAttribute('class', 'aem-Grid aem-Grid--12 aem-Grid--default--12 ');
    const divEl4 = document.createElement('div');
    divEl4.setAttribute('class', 'container responsivegrid d_footerSecondary aem-GridColumn aem-GridColumn--default--12');
    const divEl5 = document.createElement('div');
    divEl5.setAttribute('id', 'container-ba88f36121');
    divEl5.setAttribute('class', 'cmp-container');
    divEl5.setAttribute('style', 'background-image:url()');
    const divEl6 = document.createElement('div');
    divEl6.setAttribute('class', 'aem-Grid aem-Grid--12 aem-Grid--default--12 ');
    const divEl7 = document.createElement('div');
    divEl7.setAttribute('class', 'teaser aem-GridColumn--default--none aem-GridColumn aem-GridColumn--default--3 aem-GridColumn--offset--default--1');
    const divEl8 = document.createElement('div');
    divEl8.setAttribute('id', 'icon-icon-arrow');
    divEl8.setAttribute('class', 'cmp-teaser');
    const aEl = document.createElement('a');
    aEl.setAttribute('class', 'cmp-teaser__link');
    aEl.setAttribute('href', '/in/en/forms/book-a-test-ride/');
    const divEl9 = document.createElement('div');
    divEl9.setAttribute('class', 'cmp-teaser__content');
    const divEl10 = document.createElement('div');
    divEl10.setAttribute('class', 'cmp-teaser__content-inner');
    const spanEl = document.createElement('span');
    divEl10.append(spanEl);
    const h2El = document.createElement('h2');
    h2El.setAttribute('class', 'cmp-teaser__title');
    h2El.textContent = 'Book a Test Ride';
    divEl10.append(h2El);
    divEl9.append(divEl10);
    aEl.append(divEl9);
    const divEl11 = document.createElement('div');
    divEl11.setAttribute('class', 'cmp-teaser__image');
    const pictureEl = document.createElement('picture');
    const sourceEl = document.createElement('source');
    sourceEl.setAttribute('media', '(max-width:767px)');
    sourceEl.setAttribute('defer', '');
    sourceEl.setAttribute('srcset', '/content/dam/RE-Platform-Revamp/re-revamp-commons/seceondoryFooterOne.webp');
    pictureEl.append(sourceEl);
    const imgEl = document.createElement('img');
    imgEl.setAttribute('class', 'cmp-image__image');
    imgEl.setAttribute('loading', 'lazy');
    imgEl.setAttribute('src', '/content/dam/RE-Platform-Revamp/re-revamp-commons/seceondoryFooterOne.webp');
    pictureEl.append(imgEl);
    divEl11.append(pictureEl);
    aEl.append(divEl11);
    divEl8.append(aEl);
    divEl7.append(divEl8);
    divEl6.append(divEl7);
    const divEl12 = document.createElement('div');
    divEl12.setAttribute('class', 'teaser aem-GridColumn--default--none aem-GridColumn aem-GridColumn--default--3 aem-GridColumn--offset--default--0');
    const divEl13 = document.createElement('div');
    divEl13.setAttribute('id', 'icon-icon-arrow');
    divEl13.setAttribute('class', 'cmp-teaser');
    const aEl2 = document.createElement('a');
    aEl2.setAttribute('class', 'cmp-teaser__link');
    aEl2.setAttribute('href', '/in/en/v4/locate-us/');
    const divEl14 = document.createElement('div');
    divEl14.setAttribute('class', 'cmp-teaser__content');
    const divEl15 = document.createElement('div');
    divEl15.setAttribute('class', 'cmp-teaser__content-inner');
    const spanEl2 = document.createElement('span');
    divEl15.append(spanEl2);
    const h2El2 = document.createElement('h2');
    h2El2.setAttribute('class', 'cmp-teaser__title');
    h2El2.textContent = 'Find a Store';
    divEl15.append(h2El2);
    divEl14.append(divEl15);
    aEl2.append(divEl14);
    const divEl16 = document.createElement('div');
    divEl16.setAttribute('class', 'cmp-teaser__image');
    const pictureEl2 = document.createElement('picture');
    const sourceEl2 = document.createElement('source');
    sourceEl2.setAttribute('media', '(max-width:767px)');
    sourceEl2.setAttribute('defer', '');
    sourceEl2.setAttribute('srcset', '/content/dam/RE-Platform-Revamp/re-revamp-commons/map-icon.png');
    pictureEl2.append(sourceEl2);
    const imgEl2 = document.createElement('img');
    imgEl2.setAttribute('class', 'cmp-image__image');
    imgEl2.setAttribute('loading', 'lazy');
    imgEl2.setAttribute('src', '/content/dam/RE-Platform-Revamp/re-revamp-commons/map-icon.png');
    pictureEl2.append(imgEl2);
    divEl16.append(pictureEl2);
    aEl2.append(divEl16);
    divEl13.append(aEl2);
    divEl12.append(divEl13);
    divEl6.append(divEl12);
    const divEl17 = document.createElement('div');
    divEl17.setAttribute('class', 'teaser aem-GridColumn--default--none aem-GridColumn aem-GridColumn--default--3 aem-GridColumn--offset--default--0');
    const divEl18 = document.createElement('div');
    divEl18.setAttribute('id', 'icon-icon-arrow');
    divEl18.setAttribute('class', 'cmp-teaser');
    const aEl3 = document.createElement('a');
    aEl3.setAttribute('class', 'cmp-teaser__link');
    aEl3.setAttribute('href', '#servicebookingtabs-2-tab');
    const divEl19 = document.createElement('div');
    divEl19.setAttribute('class', 'cmp-teaser__content');
    const divEl20 = document.createElement('div');
    divEl20.setAttribute('class', 'cmp-teaser__content-inner');
    const spanEl3 = document.createElement('span');
    divEl20.append(spanEl3);
    const h2El3 = document.createElement('h2');
    h2El3.setAttribute('class', 'cmp-teaser__title');
    h2El3.textContent = 'Book a Service';
    divEl20.append(h2El3);
    divEl19.append(divEl20);
    aEl3.append(divEl19);
    const divEl21 = document.createElement('div');
    divEl21.setAttribute('class', 'cmp-teaser__image');
    const pictureEl3 = document.createElement('picture');
    const sourceEl3 = document.createElement('source');
    sourceEl3.setAttribute('media', '(max-width:767px)');
    sourceEl3.setAttribute('defer', '');
    sourceEl3.setAttribute('srcset', '/content/dam/RE-Platform-Revamp/re-revamp-commons/rsa-icon.png');
    pictureEl3.append(sourceEl3);
    const imgEl3 = document.createElement('img');
    imgEl3.setAttribute('class', 'cmp-image__image');
    imgEl3.setAttribute('loading', 'lazy');
    imgEl3.setAttribute('src', '/content/dam/RE-Platform-Revamp/re-revamp-commons/rsa-icon.png');
    pictureEl3.append(imgEl3);
    divEl21.append(pictureEl3);
    aEl3.append(divEl21);
    divEl18.append(aEl3);
    divEl17.append(divEl18);
    divEl6.append(divEl17);
    divEl5.append(divEl6);
    divEl4.append(divEl5);
    divEl3.append(divEl4);
    const divEl22 = document.createElement('div');
    block.textContent = '';
    block.append(container);
}  