export default function decorate(block) {
    const container = document.createElement('div');
    container.setAttribute('class', 'container');
    const divEl = document.createElement('div');
    divEl.setAttribute('id', 'container-5e8e5ea7a2');
    divEl.setAttribute('class', 'cmp-container');
    divEl.setAttribute('style', 'background-image:url()');
    const divEl2 = document.createElement('div');
    divEl2.setAttribute('class', 'locateservicecentrecard');
    const sectionEl = document.createElement('section');
    sectionEl.setAttribute('class', 'section-locate-centre re-rides-home-locate-us-component');
    const divEl3 = document.createElement('div');
    divEl3.setAttribute('id', 'locateservicecentrecard-2da40d634e');
    divEl3.setAttribute('class', 'cmp-tabs locate-card-tabs');
    divEl3.setAttribute('data-cmp-is', 'tabs');
    divEl3.setAttribute('data-placeholder-text', 'false');
    const divEl4 = document.createElement('div');
    divEl4.setAttribute('class', 'locate-centre__card');
    divEl4.setAttribute('style', `background-image: url(${block.querySelector(" div:nth-child(1) > picture > img").src})`);
    const divEl5 = document.createElement('div');
    divEl5.setAttribute('class', 'locate-centre__card-flex d-flex');
    const divEl6 = document.createElement('div');
    divEl6.setAttribute('class', 'locate-centre__card-lh');
    const h3El = document.createElement('h3');
    h3El.setAttribute('class', 'locate-centre__card-head');
    h3El.textContent =  block.querySelector(" div:nth-child(2) h3").textContent ;
    divEl6.append(h3El);
    const divEl7 = document.createElement('div');
    divEl7.setAttribute('class', 'locate-centre__card-desc');
    const pEl = document.createElement('p');
    divEl7.append(pEl);
    const pEl2 = document.createElement('p');
    pEl2.textContent = block.querySelector(" div:nth-child(2) p").textContent;
    divEl7.append(pEl2);
    const pEl3 = document.createElement('p');
    divEl7.append(pEl3);
    divEl6.append(divEl7);
    divEl5.append(divEl6);
    const divEl8 = document.createElement('div');
    divEl8.setAttribute('class', 'locate-centre__card-rh');
    const labelEl = document.createElement('label');
    labelEl.setAttribute('class', 'locate-centre__field-label');
    labelEl.setAttribute('for', 'locate');
    labelEl.textContent = 'Enter your location';
    divEl8.append(labelEl);
    const divEl9 = document.createElement('div');
    divEl9.setAttribute('class', 'locate-centre__suggest-list');
    const divEl10 = document.createElement('div');
    divEl10.setAttribute('class', 'locate-centre__field');
    const inputEl = document.createElement('input');
    inputEl.setAttribute('aria-label', 'Enter location');
    inputEl.setAttribute('class', 'input-field');
    inputEl.setAttribute('id', 'locate');
    inputEl.setAttribute('name', 'locate');
    inputEl.setAttribute('placeholder', 'Enter location');
    inputEl.setAttribute('type', 'text');
    inputEl.setAttribute('ip-stack-api-key', 'd5a315b9170426997dc1172b7c7f3b61');
    inputEl.setAttribute('dealer-api', 'https://api-uat2.royalenfield.com/v3/core/dealers/dealers-around-me');
    divEl10.append(inputEl);
    const imgEl = document.createElement('img');
    imgEl.setAttribute('loading', 'lazy');
    imgEl.setAttribute('alt', 'cdc');
    imgEl.setAttribute('class', 'locate-centre__locate-icon');
    imgEl.setAttribute('src', 'https://stagecdn.royalenfield.com/content/dam/RE-Platform-Revamp/rides-landing-/gps_search_icon.png');
    imgEl.setAttribute('title', 'cdc');
    divEl10.append(imgEl);
    divEl9.append(divEl10);
    divEl8.append(divEl9);
    const labelEl2 = document.createElement('label');
    labelEl2.setAttribute('class', 'locate-centre__tab-label');
    labelEl2.textContent = 'Search for:';
    divEl8.append(labelEl2);
    const olEl = document.createElement('ol');
    olEl.setAttribute('role', 'tablist');
    olEl.setAttribute('class', 'cmp-tabs__tablist');
    olEl.setAttribute('aria-multiselectable', 'false');
    const liEl = document.createElement('li');
    liEl.setAttribute('role', 'tab');
    liEl.setAttribute('id', 'locatecard-1-tab');
    liEl.setAttribute('class', 'cmp-tabs__tab tab-listing cmp-tabs__tab--active');
    liEl.setAttribute('tabindex', '0');
    liEl.setAttribute('data-cmp-hook-tabs', 'tab');
    liEl.setAttribute('aria-selected', 'true');
    liEl.setAttribute('search-type', 'dealer');
    liEl.textContent = 'Store';
    olEl.append(liEl);
    const liEl2 = document.createElement('li');
    liEl2.setAttribute('role', 'tab');
    liEl2.setAttribute('id', 'locatecard-2-tab');
    liEl2.setAttribute('class', 'cmp-tabs__tab tab-listing');
    liEl2.setAttribute('tabindex', '-1');
    liEl2.setAttribute('data-cmp-hook-tabs', 'tab');
    liEl2.setAttribute('aria-selected', 'false');
    liEl2.setAttribute('search-type', 'serviceCentres');
    liEl2.textContent = 'Service Center';
    olEl.append(liEl2);
    const liEl3 = document.createElement('li');
    liEl3.setAttribute('role', 'tab');
    liEl3.setAttribute('id', 'locatecard-3-tab');
    liEl3.setAttribute('class', 'cmp-tabs__tab tab-listing');
    liEl3.setAttribute('tabindex', '-1');
    liEl3.setAttribute('data-cmp-hook-tabs', 'tab');
    liEl3.setAttribute('aria-selected', 'false');
    liEl3.setAttribute('search-type', 'spareParts');
    liEl3.textContent = 'Genuine Parts Distributor';
    olEl.append(liEl3);
    divEl8.append(olEl);
    divEl5.append(divEl8);
    divEl4.append(divEl5);
    const divEl11 = document.createElement('div');
    divEl11.setAttribute('id', 'locatecard-1');
    divEl11.setAttribute('role', 'tabpanel');
    divEl11.setAttribute('aria-labelledby', 'locatecard-1-tab');
    divEl11.setAttribute('tabindex', '0');
    divEl11.setAttribute('class', 'cmp-tabs__tabpanel');
    divEl11.setAttribute('data-cmp-hook-tabs', 'tabpanel');
    const divEl12 = document.createElement('div');
    divEl12.setAttribute('class', 'locatecardtabs tabs panelcontainer');
    const divEl13 = document.createElement('div');
    divEl13.setAttribute('class', 'cmp-tabs locate-tabs__overlay stores-tab');
    const divEl14 = document.createElement('div');
    divEl14.setAttribute('class', 'locate-center__listing-wrap');
    const divEl15 = document.createElement('div');
    divEl15.setAttribute('class', 'locate-center__listing d-flex');
    divEl15.setAttribute('id', 'locateListing');
    divEl14.append(divEl15);
    divEl13.append(divEl14);
    divEl12.append(divEl13);
    divEl11.append(divEl12);
    divEl4.append(divEl11);
    const divEl16 = document.createElement('div');
    divEl16.setAttribute('class', 'locate-center__listing-wrap');
    const divEl17 = document.createElement('div');
    divEl17.setAttribute('class', 'd-flex locate-center__results-wrap d-none');
    const aEl = document.createElement('a');
    aEl.setAttribute('data-href', 'https://stagecdn.royalenfield.com/content/royal-enfield/in/en/rides-revamp-pages/rides-detail-page.html');
    aEl.setAttribute('class', 'custom-btn results-cta arrow-r locate-view-more-cta');
    aEl.setAttribute('target', '_self');
    aEl.setAttribute('title', 'VIEW MORE');
    aEl.textContent = 'View More';
    divEl17.append(aEl);
    divEl16.append(divEl17);
    const divEl18 = document.createElement('div');
    divEl18.setAttribute('class', 'd-none no-results');
    const pEl4 = document.createElement('p');
    pEl4.textContent = 'No result found';
    divEl18.append(pEl4);
    divEl16.append(divEl18);
    divEl4.append(divEl16);
    divEl3.append(divEl4);
    sectionEl.append(divEl3);
    divEl2.append(sectionEl);
    const scriptEl = document.createElement('script');
    scriptEl.setAttribute('type', 'text/javascript');
    scriptEl.setAttribute('src', '');
    divEl2.append(scriptEl);
    const scriptEl2 = document.createElement('script');
    scriptEl2.setAttribute('id', 'locateScript');
    scriptEl2.setAttribute('type', 'text/x-handlebars-template');
    scriptEl2.textContent = '{{#each this}} <div class="locate-center__item"> <a href="/content/dam" title="Ess Arr Motors" target="_self" class="custom-btn locate-center__name">{{this.branchName}}</a> <div class="d-flex locate-center__deets"> <div class="locate-center__rating d-flex"> <div class="rating-star-box"> <div class="rating-star"> <span class="reIcon-star"></span> </div> <div class="rating-star-filled"> <span class="reIcon-star-filled"></span> </div> </div> <span>{{this.googleRating}}</span> </div> <p class="locate-center__dist"> {{this.distance}} km away </p> <!--<div class="locate-center__timing d-flex"> <p class="locate-center__opening">{{this.GmbOpenStatus}}</p> <p class="locate-center__closing"> Closes 11:30 pm </p> </div>--> <a href="tel:{{this.phone}}" title="custom-btn" class="custom-btn locate-center__call" target="_self"> <img loading="lazy" src="/content/dam/RE-Platform-Revamp/call.svg" alt="Call" title="Call" class="locate-center__call-icon"> {{this.phone}} </a> </div> <p class="locate-center__address"> {{this.addressLine1}}, {{this.addressLine2}}, {{this.Locality}} </p> <div class="d-flex"> <a href="https://www.google.com/maps/place/?q=place_id:{{this.googlePlaceId}}" target="_blank" rel="nofollow" title="get-direction" class="custom-btn cta-yellow">GET DIRECTIONS</a> </div> </div> {{/each}}';
    divEl2.append(scriptEl2);
    divEl.append(divEl2);
    container.append(divEl);
    block.textContent = '';
    block.append(container);
}